config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "top#index"

  resources :users, only: [:show, :edit, :update]
  resources :free_posts, only: [:show, :edit, :update, :new, :create, :index, :destroy]  do
    resources :comments, only: [:create]
  end  

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy, :index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :free_post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/free_post.rb
class FreePost < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  mount_uploader :image, ImageUploader

  has_many :free_posts, ->{ order("created_at DESC") }
  has_many :comments

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships


  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.create(text: comment_params[:text],free_post_id: comment_params[:free_post_id], user_id: current_user.id)

    if @comment.save
      @free_post = FreePost.find(params[:free_post_id]) 
      @user = FreePost.find(params[:free_post_id]).user.user_name
      @email = FreePost.find(params[:free_post_id]).user.email
      CommentMailer.receive_when_comment(@free_post, @user, @email).deliver
    end

    redirect_to free_post_path(@comment.free_post_id)
  end


  private
  def comment_params
     params.permit(:text, :free_post_id).merge(user_id: current_user.id)
  end
end

app/controllers/free_posts_controller.rb
class FreePostsController < ApplicationController
  def index
    @free_posts = FreePost.order("created_at DESC")
  end

  def new
    @free_post = FreePost.new
  end

  def show
    @free_post = FreePost.find(params[:id])
    # binding.pry
    lat_position = @free_post.lat_pos
    lng_position = @free_post.lng_pos

    gon.lat_position_js = lat_position
    gon.lng_position_js = lng_position

    @comments = @free_post.comments
  end

  def create
    @free_post = FreePost.create(create_params)

    if @free_post.save
      redirect_to :root, notice: 'Succeeded Free Post'
    else
      redirect_to :root, alert: 'Missed Free Post'
    end
  end

  def destroy
    free_post = FreePost.find(params[:id])
    if free_post.user_id == current_user.id
      free_post.destroy
      if free_post.destroy
        redirect_to :root, notice: 'Destroyed the Free Post'
      else
        redirect_to :root, alert: 'Missed Destroying the Free Post'
      end
    end
    
  end


  def edit
    @free_post = FreePost.find(params[:id])
  end

  def update
    free_post = FreePost.find(params[:id])
    if free_post.user_id == current_user.id
      free_post.update(create_params)
      if free_post.save
         redirect_to free_post_path(free_post.id), notice: 'Succeeded The Free Post Update'
      else 
         redirect_to free_post_path(free_post.id), alert: 'Missed The Free Post Update'
      end
    end
  end


  private
  def create_params
    params.require(:free_post).permit(:start_time, :end_time, :place, :detail, :lat_pos, :lng_pos).merge(user_id: current_user.id)
    
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    respond_to do |format|
     format.html { redirect_to @user }
     format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    respond_to do |format|
    format.html { redirect_to @user }
    format.js
    end
  end



  def index
    now_time = Time.zone.now

    start_date = Time.zone.now
    end_date = start_date + 259200

    following_ids = "SELECT following_id FROM relationships WHERE follower_id = :user_id"
    @follow_posts = FreePost.where("user_id IN (#{following_ids})OR user_id = :user_id", user_id: current_user.id).order('created_at desc').page(params[:page]).per(20)

    @free_posts = FreePost.where("user_id IN (#{following_ids})OR user_id = :user_id", user_id: current_user.id).where(end_time: start_date..end_date).order('created_at desc').page(params[:page]).per(20)

    gon.free_posts_js = @free_posts

  end

  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

    now_time = Time.zone.now

    start_date = Time.zone.now
    end_date = start_date + 259200
    
    @free_posts = FreePost.where(end_time: start_date..end_date)

    gon.free_posts_js = @free_posts

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    # binding.pry
    @user = User.find(params[:id])
    @free_posts = FreePost.where(user_id: params[:id]).order("created_at DESC")
  end

  def edit
    
  end

  def update
    current_user.update(update_params)
    if current_user.save
      redirect_to user_path(current_user.id), notice: 'Succeeded Your User Data Update'
    else
      redirect_to user_path(current_user.id), alert: 'Missed Your User Data Update'
    end
    
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end




  private
  def update_params
    params.require(:user).permit(:user_name, :introduction, :gender, :area, :favorite, :work, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/free_posts_helper.rb
module FreePostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
     user == current_user
  end

end

app/views/common/_footer.html.erb
<div class="col-xs-12 footer-box">
  <p class="text-center">IN MY BOOK, Inc. All Right Reserved</p>
</div>

app/views/common/_header.html.erb
<div class="navbar">

<div class="navbar-header">
  <%= link_to image_tag("LogoFactory.jpg", {height:100}), root_path %>  
</div>



<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right tb-center">
    <li><%= link_to "マイページ", user_path(current_user), method: :get %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
  </ul>
 
<% end %>

<% unless user_signed_in? %>
  <ul class="nav navbar-nav navbar-right tb-center"> 
    <li><%= link_to "ログイン", "/users/sign_in" %></li>
    <li><%= link_to "ユーザー登録", new_user_registration_path, method: :get %></li>
  </div>

<% end %>

</div>


<div>
  <i class="fa fa-list-alt" aria-hidden="true"></i><%= link_to "フリータイム一覧", free_posts_path %>
  <% if user_signed_in? %><i class="fa fa-users" aria-hidden="true"></i>
    <%= link_to "フォローユーザーの投稿一覧", relationships_path %>
  <i class="fa fa-pencil" aria-hidden="true"></i><%= link_to "フリータイムを投稿", new_free_post_path, method: :get %>
   <% end %>
</div>

app/views/free_posts/_free_post_display.html.erb
<% start_time = f.start_time.to_s.gsub(":00 +0900", "") %>
<% end_time = f.end_time.to_s.gsub(":00 +0900", "") %>

<div class="col-xs-6 index-box">
  <div class="col-xs-3">
    <%= link_to image_tag(f.user.image.url(:thumb), class: "img-circle"), user_path(f.user) %>
  </div>
  <div class="col-xs-9">
    <%= start_time %> ~ <%= end_time %></br>
    <%= f.place %></br>
    <p class="index-detail"><%= f.detail %><p>
    <%= f.user.user_name %></br>
  
    <%= link_to '詳細', free_post_path(f.id), method: :get %>
  </div>
</div>

app/views/free_posts/edit.html.erb
<div id="map"></div>
<!-- <ul>
    <li>lat: <span id="lat"></span></li>
    <li>lng: <span id="lng"></span></li>
</ul>
 -->
<div class="show-box">
  <%= form_for(@free_post)  do |f| %>
    <div class="form-group">
      <%= f.label :lat, "緯度: " %>
      <%= f.text_field :lat_pos, value:"Mapをクリック", id: 'lat_field', class: "form-inline" %>
      <%= f.label :lng, "経度: " %><%= f.text_field :lng_pos, value:"Mapをクリック", id: 'lng_field', class: "form-inline" %>
    </div>
    <div>
      <dl>
        <dt><%= f.label :place, "場所" %></dt>
        <dl><%= f.text_field :place , class: "form-control" %></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :start_time, "フリータイム（開始）" %></dt>
        <dl><%= f.datetime_select :start_time , class: "form-control"%></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :start_time, "フリータイム（終了）" %></dt>
        <dl><%= f.datetime_select :end_time %></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :detail, "詳細" %></dt>
        <dl><%= f.text_area :detail, class: "form-control" %></dl>
      </dl>
    </div>
    <%= f.submit "編集完了", class: "btn btn-success" %>

  <% end %>
</div>

<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 35.667529, lng: 139.713815},
          zoom: 15
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // //マーカーの初期設定
        // let marker = new google.maps.Marker({
        //   position: (35.40, 139.42),
        //   map: myMap
        // })

        let marker = "";
        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            // infoWindow.setPosition(pos);
            // infoWindow.setContent('Your Position.');
            marker = new google.maps.Marker({
              map : map,             // 対象の地図オブジェクト
              position : pos   // 緯度・経度
            });

            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }



        map.addListener('click', function(e) {
        // marker.setMap(null);
        marker.setMap(null);
        marker = new google.maps.Marker({
          position: e.latLng,
          map: map
          });
        getClickLatLng(e.latLng, map);
      });
      }



    function getClickLatLng(lat_lng, map) {

      // 座標を表示
      // document.getElementById('lat_field').textContent = lat_lng.lat();
      // document.getElementById('lng').textContent = lat_lng.lng();
      //座標をフォームに入れる
      document.getElementById('lat_field').value = lat_lng.lat();
      document.getElementById('lng_field').value= lat_lng.lng();
      // マーカーを設置
      // marker = new google.maps.Marker({
      // position: lat_lng,
      // map: map
      // });

      

      // 座標の中心をずらす
      // http://syncer.jp/google-maps-javascript-api-matome/map/method/panTo/
      map.panTo(lat_lng);
    }
  </script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDUJ7YNNwefaUIeD3iBHnIz7ls91TN-l8&callback=initMap">
</script>

app/views/free_posts/index.html.erb
<% @free_posts.each do |f| %>
  <%= render partial: "free_posts/free_post_display", locals: {f: f} %>
<% end %>

app/views/free_posts/new.html.erb
<div id="map"></div>
<!-- <ul>
    <li>lat: <span id="lat"></span></li>
    <li>lng: <span id="lng"></span></li>
</ul>
 -->
<div class="show-box">
  <%= form_for(@free_post)  do |f| %>
    <div class="form-group">
      <%= f.label :lat, "緯度: " %>
      <%= f.text_field :lat_pos, value:"Mapをクリック", id: 'lat_field', class: "form-inline" %>
      <%= f.label :lng, "経度: " %><%= f.text_field :lng_pos, value:"Mapをクリック", id: 'lng_field', class: "form-inline" %>
    </div>
    <div>
      <dl>
        <dt><%= f.label :place, "場所" %></dt>
        <dl><%= f.text_field :place , class: "form-control" %></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :start_time, "フリータイム（開始）" %></dt>
        <dl><%= f.datetime_select :start_time , class: "form-control"%></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :start_time, "フリータイム（終了）" %></dt>
        <dl><%= f.datetime_select :end_time %></dl>
      </dl>
    </div>

    <div>
      <dl>
        <dt><%= f.label :detail, "詳細" %></dt>
        <dl><%= f.text_area :detail, class: "form-control" %></dl>
      </dl>
    </div>
    <%= f.submit "投稿", class: "btn btn-success" %>

  <% end %>
</div>

<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 35.667529, lng: 139.713815},
          zoom: 15
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // //マーカーの初期設定
        // let marker = new google.maps.Marker({
        //   position: (35.40, 139.42),
        //   map: myMap
        // })

        let marker = "";
        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            // infoWindow.setPosition(pos);
            // infoWindow.setContent('Your Position.');
            marker = new google.maps.Marker({
              map : map,             // 対象の地図オブジェクト
              position : pos   // 緯度・経度
            });

            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }



        map.addListener('click', function(e) {
        // marker.setMap(null);
        marker.setMap(null);
        marker = new google.maps.Marker({
          position: e.latLng,
          map: map
          });
        getClickLatLng(e.latLng, map);
      });
      }



    function getClickLatLng(lat_lng, map) {

      // 座標を表示
      // document.getElementById('lat_field').textContent = lat_lng.lat();
      // document.getElementById('lng').textContent = lat_lng.lng();
      //座標をフォームに入れる
      document.getElementById('lat_field').value = lat_lng.lat();
      document.getElementById('lng_field').value= lat_lng.lng();
      // マーカーを設置
      // marker = new google.maps.Marker({
      // position: lat_lng,
      // map: map
      // });

      

      // 座標の中心をずらす
      // http://syncer.jp/google-maps-javascript-api-matome/map/method/panTo/
      map.panTo(lat_lng);
    }
  </script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDUJ7YNNwefaUIeD3iBHnIz7ls91TN-l8&callback=initMap">
</script>

app/views/free_posts/show.html.erb
<div id="map"></div>

<div class="show-box">
  <dl>
    <dt>フリータイム</dt>
    <% start_time = @free_post.start_time.to_s.gsub(":00 +0900", "") %>
    <% end_time = @free_post.end_time.to_s.gsub(":00 +0900", "") %>
    <dd><%= start_time %> ~ <%= end_time %></dd>
  </dl>
  <dl>
    <dt>場所</dt>
    <dl><%= @free_post.place %></dl>
  </dl>
  <dl>
    <dt>詳細</dt>
    <dd><%= simple_format(@free_post.detail) %></dd>   
  </dl>
 
  <dl>
    <dt>開催者</dt>
    <dd> <%= link_to image_tag(@free_post.user.image.url(:thumb), class: "img-circle"), user_path(@free_post.user) %></dd>
    <dd><%= @free_post.user.user_name %></dd>   
  </dl>


  <% if user_signed_in? %>
    <% if @free_post.user.id == current_user.id %>
      <ul class="list-unstyled list-inline">
        <li><%= link_to '編集', edit_free_post_path(@free_post.id), method: :get %></li>
        <li><%= link_to '削除', free_post_path(@free_post.id), method: :delete, id: "delete-btn" %></li>
      </ul>
    <% end %>
  <% end %>
  
</div>

<% if user_signed_in? %>
    <div class="form-group">
      <%= form_tag("/free_posts/#{@free_post.id}/comments", method: :post) do |comments| %>
        <div class="line-break comment-field"><%= text_area_tag :text, "", rows: "4", maxlength: 200, required: true, class: "form-control" %></div>
        <%= submit_tag "コメントを投稿", class: "btn btn-success"%>
      <% end %>
    </div>
  <% end %>


 <% if @comments %>
    <% @comments.each do |comment| %>
      <div class="each-comment line-break">
      <p><%= simple_format(comment.text) %></p>
      <p class="gray-text comment-foot"><%= link_to comment.user.user_name, user_path(comment.user) %>
      <%= comment.created_at %></p>
      </div>
    <% end %>
  <% end %>

<script>

gon.lat_position_js = +gon.lat_position_js;
gon.lng_position_js = +gon.lng_position_js;

    function initMap() {
        let pos = {
          lat: gon.lat_position_js, 
          lng: gon.lng_position_js};


        var map = new google.maps.Map(document.getElementById('map'), {
          center: pos,
          zoom: 15
        });

        var infoWindow = new google.maps.InfoWindow({map: map});

        //マーカーの初期設定
        let marker = new google.maps.Marker({
          position: pos,
          map: map
        });

        
      };
      

</script>


<script>
  $("#delete-btn").on("click", function(){
    if(!confirm('本当に削除しますか？')){
        /* キャンセルの時の処理 */
        return false;
    }else{
        /*　OKの時の処理 */
        location.href = 'index.html';
    }
  })
</script>


<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDUJ7YNNwefaUIeD3iBHnIz7ls91TN-l8&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Free Meet!</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


</head>

<body class="container">
  <%= render partial: 'common/header' %>
  <p class="notice alert-success"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <div id="share"></div>

  <%= render partial: 'common/footer' %>

    <script>
        $("#share").jsSocials({
            shares: ["email", "twitter", "facebook", "googleplus","whatsapp"]
        });
    </script>

</body>

</html>

app/views/relationships/create.js.erb
//フォロー、アンフォロー切り替え
$("#follow_form<%= @user.id %>").html("<%= j render 'users/unfollow' %>");

//フォロー数の切り替え
$("#stats-count").html("<%= j render 'users/stats' %>");

app/views/relationships/destroy.js.erb
//フォロー、アンフォロー切り替え
$("#follow_form<%= @user.id %>").html("<%= j render 'users/follow' %>");

$("#stats-count").html("<%= j render 'users/stats' %>");

app/views/relationships/index.html.erb
<div id="map-top"></div>

<% @follow_posts.each do |f| %>
  <%= render partial: "free_posts/free_post_display", locals: {f: f} %>
<% end %>


<script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.

      let lat_pos_i = 0;
      let lng_pos_i = 0;
      let free_name = "";
      let free_start = "";
      let free_end = "";
      let free_place = "";


      function initMap() {
        var map = new google.maps.Map(document.getElementById('map-top'), {
          center: {lat: 35.667529, lng: 139.713815},
          zoom: 15
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent('現在地');
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }

        for(let i=0; i<gon.free_posts_js.length; i++){
          lat_pos_i = +gon.free_posts_js[i].lat_pos;
          lng_pos_i = +gon.free_posts_js[i].lng_pos;
          free_place = gon.free_posts_js[i].place;
          free_start_g = gon.free_posts_js[i].start_time;
          free_start_gr = free_start_g.replace(":00.000+09:00","");
          free_start = free_start_gr.replace("T", "-")
          free_end_g = gon.free_posts_js[i].end_time;
          free_end_gr = free_end_g.replace(":00.000+09:00","");
          free_end = free_end_gr.replace("T", "-");
          free_detail = gon.free_posts_js[i].detail;
          free_post_id = +gon.free_posts_js[i].id;

          // console.log(free_start);

          db_info = `${free_place}<br>${free_start}~${free_end}<br>${free_detail}<br><a href="/free_posts/${free_post_id}">個別ページ</a>`;

          db_pos = {
                lat: lat_pos_i,
                lng: lng_pos_i
              };

          let marker = new google.maps.Marker({
              map : map,             // 対象の地図オブジェクト
              position : db_pos   // 緯度・経度
          });

          let infoWindow = new google.maps.InfoWindow({ // 吹き出しの追加
                content: 
                  db_info
                   // 吹き出しに表示する内容
            });

          marker.addListener('click', function() { // マーカーをクリックしたとき
            infoWindow.open(map, marker); // 吹き出しの表示
          });


        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDUJ7YNNwefaUIeD3iBHnIz7ls91TN-l8&callback=initMap">
    </script>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id), remote: true) do |f| %>
  <%= f.hidden_field :following_id %>
  <%= f.submit "Follow", class: "btn btn-large btn-success follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
  <%= link_to "#{@user.followings.count}", following_user_path(@user), method: :get %>
  following / 
  <%= link_to "#{@user.followers.count}", followers_user_path(@user), method: :get %>
  followers

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-success follow-btn" %>
<% end %>

app/views/users/show.html.erb
  <div class="col-xs-6">
    <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
      <i class="fa fa-address-book" aria-hidden="true"></i><%= link_to "プロフィール編集", edit_user_path%></br>
      <% end %>
    <% end %>
    <div>
      <%= image_tag @user.image.url(:middle), class: "img-circle img-center" %>
    </div>  
    <div class="text-center">
      <div id="stats-count">
        <%= render 'stats' %>
      </div>
      <% if user_signed_in? %>
        <div id="follow_form<%= @user.id %>">
          <%= render 'follow_form' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-xs-6 mypage-box">
    <dl>
      <dt>ユーザーネーム</dt>
      <dd><%= @user.user_name %></dd>
    </dl>
    <dl>
      <dt>自己紹介</dt>
      <dd><%= simple_format(@user.introduction) %></dd>
    </dl>
    <dl>
      <dt>性別</dt>
      <dd><%= @user.gender %></dd>
    </dl>
    <dl>
      <dt>地域</dt>
      <dd><%= @user.area %></dd>
    </dl>
    <dl>
      <dt>趣味</dt>
      <dd><%= @user.favorite %></dd>
    </dl>
    <dl>
      <dt>職業</dt>
      <dd><%= @user.work %></dd>
    </dl>
  </div>

  <h4>>><%= @user.user_name %>さんの投稿</h4>
  <div>
  <% @free_posts.each do |f| %>
  <%= render partial: "free_posts/free_post_display", locals: {f: f} %>
  <% end %>
  </div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table class="follow-table">
<tr>
  <td class="col-xs-4"><%= link_to image_tag(user.image.url(:thumb), class: "img-circle"), user_path(user) %></td>
  <td class="col-xs-4"><%= user.user_name %></td>
  <td class="col-xs-4"><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>